name = "ahmedimtiazkhanportfolio"
compatibility_date = "2024-01-01"

[site]
bucket = "./public"
entry-point = "workers-site"

[build]
command = "npm run build"
upload.format = "service-worker"

[env.production]
workers_dev = true
route = ""
zone_id = ""

[env.production.vars]
ENVIRONMENT = "production"

[env.production.rules]
type = "Data"
globs = ["**/*.json"]
fallthrough = true

[env.production.rules.headers]
type = "Headers"
globs = ["**/*"]
fallthrough = true

[env.production.rules.headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Headers = "Content-Type"

pages_build_output_dir = "public"
